### ISSUE TITLE
It dosen't plaay music..

### ISSUE THREAD

**Issue by Jordaar** [moonstar-x/discord-music-24-7#11]
I've deployed the bot on heroku and have setup all the requirements such as Procfile which declares worker as npm start but I don't know why it is not playing music...I does connect to voice channel but don't play music :(

**Comment by Jordaar** [comment]
![image](https://user-images.githubusercontent.com/69628820/90252998-13480300-de5e-11ea-9d1d-58322afd4188.png)

**Comment by Jordaar** [comment]
It shows this but does not play anything

**Comment by moonstar-x** [comment]
This is most likely an issue with ffmpeg because you're not including it on your heroku. Since ffmpeg is a binary non related to node, the way you utilize it in heroku is different.

On your heroku application, head over to settings and then, under buildpacks, add the following:

```text
https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
```

And finally restart the dyno.

This will install ffmpeg on your dyno.

**Comment by Jordaar** [comment]
Thanks @moonstar-x  !

**Comment by moonstar-x** [comment]
Did it work? Confirm me this please so I can close this issue.

**Comment by Jordaar** [comment]
working on it..please wait.

**Comment by Jordaar** [comment]
Yessssssssss! Thanks dude! @moonstar-x thanks a lot...
