### ISSUE TITLE
Presence not working

### ISSUE THREAD

**Issue by sopergoras123** [moonstar-x/discord-music-24-7#17]
Presence updated to undefined

**Comment by moonstar-x** [comment]
Are you running the latest version  of the bot? Your `package.json` should say `"version": "2.0.0"`. Or, if you run:

```
git pull origin master
```

it should get you to the last version.

(This was a bug that happened before but I'm sure that this shouldn't be happening here anymore.)

**Comment by sopergoras123** [comment]
It says 2.0.0 i manually installed ffmpeg and ffmpeg-static

**Comment by moonstar-x** [comment]
Do sou have any console logs that you can share? Are you getting any error?

**Comment by sopergoras123** [comment]
![image](https://user-images.githubusercontent.com/61477808/97788254-5ba2d180-1bc0-11eb-8fcc-2965f8791622.png)
as you can see the song title stays as undefined

**Comment by moonstar-x** [comment]
I see, can you post here the content of your `queue.txt` file please so I can check what link is producing this error?

**Comment by sopergoras123** [comment]
![image](https://user-images.githubusercontent.com/61477808/97789254-abd16200-1bc7-11eb-88a3-04ae232ebdbd.png)

**Comment by moonstar-x** [comment]
The problem should be fixed with #18, please update your bot by either downloading the zip of the master's branch or by running (if you cloned the repo):

```
git pull origin master
```

Also, you'll most likely need to remove the `node_modules` folder and run:

```
npm install
```

before running the bot.

I'm going to close this Issue, if you come across any other problem feel free to open a new issue. Thanks for your report!
