### ISSUE TITLE
Music does not resume after it has been paused for a long time.

### ISSUE THREAD

**Issue by hezaaheza** [moonstar-x/discord-music-24-7#22]
hello there, sorry for bothering you. 
i found an issue, when the bot pausing music for 2 hours and then when someone is joining to the voice chat, the bot wont resuming the playing music until i restart the dyno from heroku.
do you have any idea how to fix it? 

![image](https://user-images.githubusercontent.com/53120237/101270817-76fc9000-37af-11eb-81ce-e1c1419e1fb1.png)
![image](https://user-images.githubusercontent.com/53120237/101270822-7cf27100-37af-11eb-9aad-a7ce25866f58.png)
np: sorry if my english not so good, i hope you understand what i say xD

**Comment by moonstar-x** [comment]
Can you send a screenshot of the console logs for whenever this happens? You should be able to see this on Heroku if you click on "More" (above right) and then "Show Logs".

**Comment by hezaaheza** [comment]
i dont see any error here. idk what happend with this

![image](https://user-images.githubusercontent.com/53120237/101270970-1c643380-37b1-11eb-9b6a-2600042830b2.png)

**Comment by moonstar-x** [comment]
Okay. I fear it's one of the two things.

1. The voice connection gets expired since the bot hasn't sent any packets during the whole time it's been there and doesn't renew the connection whenever someone joins. (Somewhat unlikely since no error is showing up related to an invalid voice connection.)
2. The youtube stream gets expired because of the whole time that has passed. (Somewhat likely since no error is showing up. :( )

If the first one is the culprit then I imagine the best solution would be to make the bot leave the channel whenever nobody is present in it.

If the second one is the one then probably the best bet would be to skip the song that was paused and continue  with the next one. That or use a library that supports seeking since I think the one that is currently used does not. But then again the problem is that since multiple providers are currently supported (Youtube, Soundcloud) and more will be, I think the maybe the aforementioned should be the next course of action.

Anyways, thanks for this report, I'll check out what I can do once these two weeks end since I'm super busy with college.

**Comment by hezaaheza** [comment]
ahh, okay mate.. thanks for answering me. maybe i'll should remove  this code from player.js
if (this.listeners > 0) {
      return this.resumeDispatcher();
    }

**Comment by moonstar-x** [comment]
If you want a quick and dirty solution so that the bot never pauses the music, replacing:

```js
updateDispatcherStatus() {
    if (!this.dispatcher) {
      return null;
    }
    
    if (this.listeners > 0) {
      return this.resumeDispatcher();
    }

    return this.pauseDispatcher();
  }
```

with:

```js
updateDispatcherStatus() {
    if (!this.dispatcher) {
      return null;
    }
    
    return this.resumeDispatcher();
  }
```

should do the trick.

**Comment by hezaaheza** [comment]
i found onething.  now my bot playing music after i rejoining the voice 20x times XD.  and then my bot like skiping the music into the next queue 
(i didnt change anything yet)

**Comment by moonstar-x** [comment]
Hey there, to somewhat fix this I decided to make the streams expire after two hours which means that if the bot has been paused for over two hours the song will just skip. (I mean, if you weren't listening to the bot for over two hours I imagine you already forgot the song you were listening to lol).

Anyways, this is done in #32. The bot has been rewritten and the file structure has changed drastically, I'm sorry if this breaks the featue that you worked on your behalf!

**Comment by hezaaheza** [comment]
Well thanks for your hardwork sir.. goodjob :D 
have a good day sir

**Comment by hezaaheza** [comment]
hello there... 
i found an issue... command not function after deploying to heroku..
i tried to type !skip but my bot wont response the song.. and i dont know what happend.. can you help me? 
and also there no error in the logs
![image](https://user-images.githubusercontent.com/53120237/103990544-fb359f00-51c3-11eb-8f4e-99cfef4c15db.png)
![image](https://user-images.githubusercontent.com/53120237/103990590-0ee10580-51c4-11eb-9564-fef60ec9645a.png)

**Comment by moonstar-x** [comment]
Are you sure that `dj!` is the prefix of the bot? Try with the default `!` and see if it works. If it works it's because you need to set up an environment variable called `PREFIX` on your Heroku (inside Settings).

Now that I realize I think the `app.json` file for the Heroku deploy isn't complete so thanks for the heads up.
