### ISSUE TITLE
Can you please update on what is happening with youtube-cookie removing feature??

### ISSUE THREAD

**Issue by Slowgamer** [moonstar-x/discord-music-24-7#40]
Like your bot is very good I mean literally appreciable but I wanna know about YouTube cookie removing thing??

**Comment by moonstar-x** [comment]
Hey there, I'm sorry but I don't think I understand properly what your question is about.

YouTube has some limitations when using it extraofficially like how the library I use for YouTube support does. Technically YouTube does not allow downloading videos from their platform, this includes streaming their content in another platform such as Discord.

By default, the library does a request to YouTube to try and get the video anonymously, however YouTube will block further requests if the requesting party has been using the platform repeatedly from the same IP and with no authentication. Due to this, it's possible that you may receive a `429` error if using the bot constantly. This problem is supposed to be mitigated by adding your account cookie in the request so that YouTube understands that these requests are done by you.

Specifying the cookie should technically remove this problem but as far as I've seen it doesn't work 100%. In fact there's an ongoing issue on the library's GitHub repo that still has no solution.

This is something that I can't fix sadly since other solutions require a more complex workaround that uses IP rotation, which is not free and not ideal for a bot that should be self-hosted. If this poses a problem, the best thing you could do is download the music and use the local music provider.

**Comment by moonstar-x** [comment]
I'm gonna close this because I assume that by now my previous answer has solved your doubts.

Feel free to re-open this issue if you need any more help.
