### ISSUE TITLE
Skip songs

### ISSUE THREAD

**Issue by ToastyNIck** [moonstar-x/discord-music-24-7#5]
I need a command to skip songs. The only way I have gotten it to skip a song and that is to make the bot crash and wait for it to restart. Sometime it would play the same songs.

**Comment by moonstar-x** [comment]
Hey there, the bot was designed to act as some sort of radio. I could certainly implement a skip command.

**Comment by ToastyNIck** [comment]
Take your time. I need to find a new way to host the bot. ;-;

**Comment by ezequieljpereiraa** [comment]
@moonstar-x Thanks for the Bot !!!!!!!

**Comment by Oli-idk** [comment]
a skip command would be amazing

**Comment by Jeydin21** [comment]
It's a radio lol. You can't skip songs on the radio, can you?

**Comment by moonstar-x** [comment]
> It's a radio lol. You can't skip songs on the radio, can you?

Hahaha yes, indeed it was planned to act as a radio so I never thought of making a skip command but it seems that many people want it.

I'm sorry guys, I haven't found the time to implement this, I've been way too busy with college. Quite unfortunately I don't see myself working on this anytime soon. Maybe at the end of the december since that's when my semester ends. Sorry to keep y'all waiting 😢

**Comment by Jeydin21** [comment]
You keep working toward your dream, don't let us slow you down!

**Comment by moonstar-x** [comment]
Sorry for taking way too long on this, uni has been super demanding this year with online classes. Anyways, this is done in #32.
