### ISSUE TITLE
Não tocar música

### ISSUE THREAD

**Issue by SalemStrike** [moonstar-x/discord-music-24-7#75]
#### :bug: Describe the Bug

> A clear and concise description of what the bug is.

#### :pencil2: Steps to Reproduce

> 1. Go to '...'
> 2. Type '...'
> 3. See error...

#### :confused: Expected Behavior

> A description of what you expected to get (if applicable).

#### :scroll: Log

``` text
Paste a relevant portion of the console log here.
```

#### :camera: Screenshots

> Paste a screenshot of the bug (if applicable).

#### :question: Other Information

* Node Version: `Version of the node runtime.`
Ñ toca música

**Comment by moonstar-x** [comment]
I'm assuming you're the person in the screenshot because of the same name.

![image](https://user-images.githubusercontent.com/14969195/163287531-e93d6d82-adaf-4417-8633-a8bffd21d5e3.png)

Your problem is that you don't have `ffmpeg` installed. You can install it with

```
npm install --save-dev ffmpeg-static
```

(By the way, your issue is not very descriptive, you should've uploaded the screenshot you sent me here.)
